//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTProject.Pages.RG_XMBeiAn {
    
    
    public partial class RG_XMBeiAn_Edit {
        
        /// <summary>
        /// AjaxFileUpload1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Ajax.FileUpload.AjaxFileUpload AjaxFileUpload1;
        
        /// <summary>
        /// UpdatePanel2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel2;
        
        /// <summary>
        /// btnEdit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.Button btnEdit;
        
        /// <summary>
        /// btnXZ 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.Button btnXZ;
        
        /// <summary>
        /// btnSub 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.Button btnSub;
        
        /// <summary>
        /// lblSHOpinion 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSHOpinion;
        
        /// <summary>
        /// lblTips 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTips;
        
        /// <summary>
        /// UpdatePanel1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// tdContainer 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdContainer;
        
        /// <summary>
        /// XMName_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox XMName_2021;
        
        /// <summary>
        /// XMLB_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList XMLB_2021;
        
        /// <summary>
        /// XMAddress_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox XMAddress_2021;
        
        /// <summary>
        /// XMAdd_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList XMAdd_2021;
        
        /// <summary>
        /// ToTalMoney_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBoxControls.NumericTextBox ToTalMoney_2021;
        
        /// <summary>
        /// GuiMoDJ_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList GuiMoDJ_2021;
        
        /// <summary>
        /// ZhiBiao_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox ZhiBiao_2021;
        
        /// <summary>
        /// JSDWName_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox JSDWName_2021;
        
        /// <summary>
        /// XMLXR_JS_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox XMLXR_JS_2021;
        
        /// <summary>
        /// LXDH_JS_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox LXDH_JS_2021;
        
        /// <summary>
        /// ZiZhiDJ_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox ZiZhiDJ_2021;
        
        /// <summary>
        /// ZiZhiBH_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox ZiZhiBH_2021;
        
        /// <summary>
        /// ZiZhiDJCode_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox ZiZhiDJCode_2021;
        
        /// <summary>
        /// ZiZhiDJRowGuid_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox ZiZhiDJRowGuid_2021;
        
        /// <summary>
        /// XMLXR_KS_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox XMLXR_KS_2021;
        
        /// <summary>
        /// LXDH_KS_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox LXDH_KS_2021;
        
        /// <summary>
        /// SJ_KS_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox SJ_KS_2021;
        
        /// <summary>
        /// HeTongMoney_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBoxControls.NumericTextBox HeTongMoney_2021;
        
        /// <summary>
        /// XMFZR_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox XMFZR_2021;
        
        /// <summary>
        /// YeWuFW_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox YeWuFW_2021;
        
        /// <summary>
        /// FuZaCD_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox FuZaCD_2021;
        
        /// <summary>
        /// BeiZhu_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox BeiZhu_2021;
        
        /// <summary>
        /// Status_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Status_2021;
        
        /// <summary>
        /// DWGuid_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox DWGuid_2021;
        
        /// <summary>
        /// DWName_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox DWName_2021;
        
        /// <summary>
        /// TJRGuid_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox TJRGuid_2021;
        
        /// <summary>
        /// DelStatus_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DelStatus_2021;
        
        /// <summary>
        /// lblZiZhiType 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblZiZhiType;
        
        /// <summary>
        /// DGZhuanYe 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid DGZhuanYe;
        
        /// <summary>
        /// XM_HTBA 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::HTProject.Ascx.FuJian_BA XM_HTBA;
        
        /// <summary>
        /// XM_SJHT 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::HTProject.Ascx.FuJian XM_SJHT;
        
        /// <summary>
        /// QY_CXZM 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::HTProject.Ascx.FuJian QY_CXZM;
        
        /// <summary>
        /// hiZYText 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox hiZYText;
        
        /// <summary>
        /// hiZYCode 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox hiZYCode;
        
        /// <summary>
        /// hiRYGuids 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.TextBox hiRYGuids;
        
        /// <summary>
        /// btInsertRY 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btInsertRY;
        
        /// <summary>
        /// TJDate_2021 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::Epoint.Web.UI.WebControls2X.DateTextBox TJDate_2021;
        
        /// <summary>
        /// hiQYZCD 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hiQYZCD;
        
        /// <summary>
        /// ValidationSummary1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary ValidationSummary1;
    }
}
